server:
  port: 8089

spring:
  application:
    name: STORAGE
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5430/storage
    username: postgres
    driver: org.postgresql.Drive
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_SERVICE_URL:http://localhost:9092}
    listener:
      ack-mode: manual

eureka:
  client:
    server-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/


bucketnamelist: myfirst1,mysecond2,myttree3

# work with (eureka/kafka)
sendBy: eureka