server:
  port: 8089

spring:
  application:
    name: STORAGE
  datasource:
    password: postgres
    url: jdbc:postgresql://storagedb:5432/storage
    username: postgres
    driver: org.postgresql.Drive
  kafka:
    bootstrap-servers: ${KAFKA_SERVICE_URL:http://localhost:9092}
    listener:
      ack-mode: manual

eureka:
  client:
    server-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/


bucketnamelist: myfirst1,mysecond2,myttree3

# work with (eureka/kafka)
sendBy: eureka