server:
  port: 8080

spring:
  application:
    name: RESOURCE
  datasource:
    password: postgres
    url: jdbc:postgresql://@db:5435/song
    username: postgres
    driver: org.postgresql.Drive
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 200KB
      max-file-size: 200MB
      max-request-size: 215MB

aws:
  s3:
    endpoint-url: http://localhost:4566
    bucketname: mybucket

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/
#what service used for message exchange (evreka|kafka)
changeBy: kafka

AWS_ENTRYPOINT: http://localhost:4566
EUREKA_URL: http://localhost:8761/
KAFKA_URL: http://localhost:9092/
POSTGRES_HOST: postgres
DATABASE_URL: postgresql://postgres:postgres@db:5435/song