server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: RESOURCE
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5434/metadata
    username: postgres
    driver: org.postgresql.Drive
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: user
      password: password

  kafka:
    bootstrap-servers: ${KAFKA_SERVICE_URL:http://localhost:9092}
    listener:
      ack-mode: manual
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 200KB
      max-file-size: 200MB
      max-request-size: 215MB
  influx:
    url: ${INFLUXDB_URL:http://localhost:8086}
    user: influxdb
    password: influxdb
    token: axOztm3DugbTq5O9TSL65mP3aFSHbzOVQ6HI-cYarLNyH6JJfE8jt_6xq2LBsZw61ICMIVVuVMUuvFg00hup1A==
    bucket: influxdbbucket
    org: influxdborg
    database: influxdb

aws:
  s3:
    endpoint-url: ${KAFKA_SERVICE_URL:http://localhost:4566}
    bucketname: mybucket

eureka:
  client:
    server-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
#what service used for message exchange (evreka|kafka)
changeBy: evreka

