server:
  port: 8083

spring:
  application:
    name: PARSER
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5435/song
    username: postgres
    driver: org.postgresql.Drive
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual


eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/

EUREKA_URL: http://localhost:8761/
#POSTGRES_HOST: jdbc:postgresql://localhost:5435/song
AWS_ENTRYPOINT: http://localhost:4566
KAFKA_URL: http://localhost:9092/
POSTGRES_HOST: postgresql://postgres:postgres@db:5435/song
