server:
  port: 8083

spring:
  application:
    name: PARSER
  datasource:
    password: postgres
    url: jdbc:postgresql://dbmeta:5432/metadata
    username: postgres
    driver: org.postgresql.Drive
  kafka:
    bootstrap-servers: ${KAFKA_SERVICE_URL:http://localhost:9092}
    listener:
      ack-mode: manual


eureka:
  client:
    server-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
