server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: RESOURCE
  datasource:
    password: postgres
    url: jdbc:postgresql:${POSTGRES_HOST_SONG:}//localhost:5435/song
    username: postgres
    driver: org.postgresql.Drive
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 200KB
      max-file-size: 200MB
      max-request-size: 215MB
  influx:
    url: http://localhost:8086
    user: influxdb
    password: influxdb
    token: axOztm3DugbTq5O9TSL65mP3aFSHbzOVQ6HI-cYarLNyH6JJfE8jt_6xq2LBsZw61ICMIVVuVMUuvFg00hup1A==
    bucket: influxdbbuck
    org: influxdborg
    database: influxdb

aws:
  s3:
    endpoint-url: http://localhost:4566
    bucketname: mybucket

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/
#what service used for message exchange (evreka|kafka)
changeBy: evreka

AWS_ENTRYPOINT: http://localhost:4566
EUREKA_URL: http://localhost:8761/
#POSTGRES_HOST: jdbc:postgresql://localhost:5435/song
KAFKA_URL: http://localhost:9092/